### ISSUE TITLE
No binary for 0.8.684.2

### ISSUE THREAD

**Issue by niuus** [HunterZ/abuse-wii#6]
Just in case you ever see this... a boot.dol was not included in the release, making it impossible to play the update.

**Comment by HunterZ** [comment]
Weird, it looks like an archive of the source rather than an actual release. Since it's been so long, I'm not sure if I even still have a working toolchain to fix it.

Maybe I can get it off of my Wii's HDD.

**Comment by niuus** [comment]
That would be cool! I would like to play this game after all this years, specially on the Wii.

**Comment by niuus** [comment]
Hi HunterZ... did you managed to find the binary in your Wii's HDD?

**Comment by niuus** [comment]
Hi HunterZ... did you manage to find the binary in your Wii's HDD?

**Comment by HunterZ** [comment]
I pulled my Wii HDD and took a look. The binary was dated 20130609, and the relevant git commits after that were text file changes, so I ported them back onto my Wii's HDD, zipped it all up, and replaced the bogus zip file: https://github.com/HunterZ/abuse-wii/releases

Give it a try and let me know how it goes.

**Comment by niuus** [comment]
Working perfectly. Now to dream about analog stick support on Gamecube controller, Classic Controller or Wii U Pro Controller so no Wiimote pointing is necessary. A man can dream ='D

Thank you very much, HunterZ!
